"""Generate Flutter's offline defaults from the API's translation catalog.

Run from any directory; use --check in validation to detect catalog drift.
"""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "localization/interface_translations.json"
TARGET = ROOT / "gospel_frontend/lib/bundled_interface_translations.dart"


def generate():
    catalogs = json.loads(SOURCE.read_text(encoding="utf-8"))
    lines = [
        "// Generated by scripts/generate_interface_translations.py. Do not edit.",
        "// dart format off",
    ]
    for language, labels in catalogs.items():
        if set(labels) != set(catalogs["english"]):
            raise ValueError(f"{language} must translate every interface key")
        lines.append(f"const {language}InterfaceTranslations = <String, String>{{")
        for key, value in labels.items():
            literal = json.dumps(value, ensure_ascii=False).replace("$", r"\$")
            lines.append(f"  '{key}': {literal},")
        lines.append("};")
    lines.append("const bundledInterfaceTranslations = <String, Map<String, String>>{")
    for language in catalogs:
        lines.append(f"  '{language}': {language}InterfaceTranslations,")
    lines.append("};")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = generate()
    if args.check:
        if not TARGET.exists() or TARGET.read_text(encoding="utf-8") != content:
            raise SystemExit("Run python3 scripts/generate_interface_translations.py")
    else:
        TARGET.write_text(content, encoding="utf-8")
