// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfXJ7PJv8BIpNF0Ee_z_64IUuU_bG7D8g',
    appId: '1:864538779408:web:5552b79e7c554e57a04f95',
    messagingSenderId: '864538779408',
    projectId: 'synopsis-224b0',
    authDomain: 'synopsis-224b0.firebaseapp.com',
    storageBucket: 'synopsis-224b0.firebasestorage.app',
    measurementId: 'G-PZN0QQ84LR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwv6Fe404ELXIZnfTXOe--__XibM7wENc',
    appId: '1:864538779408:android:d3f316dbaeb8b7d1a04f95',
    messagingSenderId: '864538779408',
    projectId: 'synopsis-224b0',
    storageBucket: 'synopsis-224b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjzYPy4jo2NKOco2akYRyNJWf2uWuuBYs',
    appId: '1:864538779408:ios:2dd53436c189b545a04f95',
    messagingSenderId: '864538779408',
    projectId: 'synopsis-224b0',
    storageBucket: 'synopsis-224b0.firebasestorage.app',
    iosBundleId: 'com.example.gospelFrontend',
  );
}
